import React from 'react';
import { BlockMath } from './Math';
import { Book, AlertTriangle, CheckCircle2 } from 'lucide-react';
import { useLanguage } from '../context/LanguageContext';

const ProductDefinitions: React.FC = () => {
  const { language } = useLanguage();

  const content = {
    EN: {
      title: "Formal Definitions",
      intro: "Let (Ei, Ti) be a family of topological spaces and E the product of Ei.",
      def1: "1. The Elementary Rectangle",
      desc1: "A subset R is an elementary rectangle if it is a product of open sets:",
      crucial: "Crucial Condition",
      crucialDesc: "For the standard product topology, we require Ui = Ei for all but a finite number of indices i.",
      def2: "2. The Product Topology",
      desc2: "The product topology on E is the topology generated by the base of all elementary rectangles.",
      consequence: "Direct Consequence: A set is open in E if and only if it is a union (finite or infinite) of elementary rectangles."
    },
    FR: {
      title: "Définitions Formelles",
      intro: "Soit (Ei, Ti) une famille d'espaces topologiques et E le produit des Ei.",
      def1: "1. Le Rectangle Élémentaire",
      desc1: "Une partie R est un rectangle élémentaire si elle est un produit d'ouverts :",
      crucial: "Condition Cruciale",
      crucialDesc: "Pour la topologie produit standard, nous imposons Ui = Ei pour tous les indices sauf un nombre fini d'entre eux.",
      def2: "2. La Topologie Produit",
      desc2: "La topologie produit sur E est la topologie engendrée par la base de tous les rectangles élémentaires.",
      consequence: "Conséquence directe : Un ensemble est ouvert dans E si et seulement s'il est une réunion (finie ou infinie) de rectangles élémentaires."
    }
  };

  const curr = content[language];

  return (
    <section className="bg-slate-50 py-16 px-6">
      <div className="mx-auto max-w-4xl">
        <div className="rounded-[2.5rem] bg-white p-10 shadow-sm border border-slate-200">
          <div className="flex items-center gap-4 mb-10">
            <div className="h-12 w-12 bg-indigo-100 rounded-2xl flex items-center justify-center text-indigo-600">
              <Book className="w-6 h-6" />
            </div>
            <h2 className="text-3xl font-bold text-slate-900 tracking-tight">{curr.title}</h2>
          </div>

          <p className="text-lg text-slate-700 mb-8 leading-relaxed">
            {curr.intro}
          </p>

          <div className="space-y-8">
            <div className="bg-indigo-50/30 p-8 rounded-3xl border border-indigo-100 shadow-sm">
               <h3 className="text-lg font-bold text-indigo-900 mb-4 flex items-center gap-2">
                 <div className="w-2 h-2 bg-indigo-500 rounded-full" />
                 {curr.def1}
               </h3>
               <p className="text-sm text-slate-600 mb-6 leading-relaxed">
                 {curr.desc1}
               </p>
               <BlockMath math="R = \\prod_{i \in I} U_i \\quad \\text{où } U_i \\in \\mathcal{T}_i" />
               <div className="mt-6 p-4 bg-white rounded-2xl border-l-4 border-amber-500 flex gap-4">
                  <AlertTriangle className="w-5 h-5 text-amber-500 shrink-0" />
                  <div>
                    <p className="text-xs font-bold text-amber-700 uppercase tracking-widest mb-1">{curr.crucial}</p>
                    <p className="text-xs text-slate-600 leading-relaxed italic">
                      {curr.crucialDesc}
                    </p>
                  </div>
               </div>
            </div>

            <div className="bg-slate-50 p-8 rounded-3xl border border-slate-200">
               <h3 className="text-lg font-bold text-slate-900 mb-4 flex items-center gap-2">
                 <div className="w-2 h-2 bg-slate-400 rounded-full" />
                 {curr.def2}
               </h3>
               <p className="text-sm text-slate-600 mb-4">
                 {curr.desc2}
               </p>
               <div className="p-4 bg-emerald-50 rounded-2xl border border-emerald-100 flex gap-3">
                  <CheckCircle2 className="w-5 h-5 text-emerald-500 shrink-0" />
                  <p className="text-xs text-emerald-800 font-bold uppercase tracking-tight">
                    {curr.consequence}
                  </p>
               </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default ProductDefinitions;
