import { createContext, useContext } from 'react';

export type Language = 'EN' | 'FR';

export interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

export const translations: Record<Language, Record<string, string>> = {
  EN: {
    // Navigation
    'nav.home': 'Home',
    'nav.intro': '1. Introduction',
    'nav.concepts': '2. Concepts',
    'nav.bases': '3. Neighborhoods & Bases',
    'nav.density': '4. Density & Separation',
    'nav.induced': '5. Induced Topology',
    'nav.product': '6. Product Topology',
    'nav.continuity': '7. Continuity & Limits',
    'nav.compact': '8. Compact Spaces',
    'nav.locallyCompact': '9. Locally Compact',
    'nav.connected': '10. Connected Spaces',
    'nav.pathConnected': '11. Path-Connectedness',
    'nav.curriculum': 'Course Curriculum',
    'nav.comingSoon': 'More topics coming soon.',
    
    // Landing Page
    'landing.title': 'Master the Geometry of',
    'landing.subtitle': 'Step away from distances and metrics. Dive into the abstract beauty of sets, neighborhoods, and continuity through interactive visualizations.',
    'landing.start': 'Start the Course',
    
    // Chapter Summaries
    'chapter.1.desc': 'Understand the 3 core axioms, open sets, and the formal definition of a topological space.',
    'chapter.2.desc': 'Explore the regions of a subset, boundary logic, and the behavior of infinite operations.',
    'chapter.3.desc': 'Understand local environments, point types (isolated/accumulation), and topological building blocks.',
    'chapter.4.desc': 'Explore "everywhere" sets like rationals and the Hausdorff property that protects point identity.',
    'chapter.5.desc': 'Learn how openness is relative to your "universe" and how to slice subspaces out of parent spaces.',
    'chapter.6.desc': 'Discover how to combine spaces using elementary rectangles and why infinite products have strict rules.',
    'chapter.7.desc': 'Generalize calculus using open sets. See how topology catches jump discontinuities and handles "holes."',
    'chapter.8.desc': 'Understand the Borel-Lebesgue property, finite subcovers, and why compactness is the gold standard.',
    'chapter.9.desc': 'Explore spaces that behave like compact sets when zoomed in, and why R succeeds while Q fails.',
    'chapter.10.desc': 'Understand topological unity through the Scissors Analogy and see how continuous functions preserve intervals.',
    'chapter.11.desc': 'Explore the geometric intuition of paths and the classic "Topologist\'s Sine Curve" exception.',
    
    // Common
    'common.next': 'Next Lesson',
    'common.chapter': 'Chapter',
    'common.continue': 'Continue the journey',
    'common.complete': 'Course Complete',
    'common.return': 'Return to the home hub.',
    'common.exercice': 'Exercise',
    'common.conclusion': 'Conclusion',
    'common.conclusion_gen': 'General Conclusion',
    'common.q': 'Question',
    'common.proof': 'Proof',
    'common.solution': 'Solution',

    // Metric Spaces Course
    'nav.metrics.intro': '1. Foundations of Distance',
    'metrics.hero.title': 'The Foundations of Distance',
    'metrics.hero.subtitle': 'Step back from abstract sets into a measurable reality. A Metric Space is a universe with a ruler, where every point has a defined numerical distance to every other point.',
    'metrics.def.title': 'Metric Space & Distance',
    'metrics.def.intro': 'Let E be a non-empty set. A distance (or metric) on E is a function d: E × E → ℝ⁺ that satisfies three strict axioms:',
    'metrics.def.ax1': '1. Separation / Identity of indiscernibles:',
    'metrics.def.ax1_sub': 'The distance between two points is zero if and only if they are identical.',
    'metrics.def.ax2': '2. Symmetry:',
    'metrics.def.ax2_sub': 'The distance from A to B is identical to the distance from B to A.',
    'metrics.def.ax3': '3. Triangle Inequality:',
    'metrics.def.ax3_sub': 'The direct path is always the shortest. Detouring through a third point will either equal or exceed the direct distance.',
    'metrics.ex.title': 'Fundamental Examples',
    'metrics.viz.title': 'The Shape of Distance',
    'metrics.viz.subtitle': 'Drag points A, B, and C to verify the Triangle Inequality across different mathematical universes.',

    // Balls and Spheres
    'nav.metrics.balls': '2. Balls and Spheres',
    'metrics.balls.hero.title': 'The Geometry of Balls and Spheres',
    'metrics.balls.hero.subtitle': 'In everyday geometry, a "ball" is a perfectly round object. However, in metric spaces, the shape of a ball is entirely dictated by the underlying distance formula. A ball can look like a circle, a diamond, or even a rigid square.',
    'metrics.balls.def.title': 'Formal Definitions',
    'metrics.balls.def.intro': 'Let (E, d) be a metric space, let a ∈ E be a center point, and let r > 0 be a real radius.',
    'metrics.balls.def.open': '1. Open Ball (Boule ouverte):',
    'metrics.balls.def.open_sub': 'The set of points strictly closer than r to a.',
    'metrics.balls.def.closed': '2. Closed Ball (Boule fermée):',
    'metrics.balls.def.closed_sub': 'The set of points at a distance less than or equal to r from a.',
    'metrics.balls.def.sphere': '3. Sphere (Sphère):',
    'metrics.balls.def.sphere_sub': 'The set of points lying exactly at a distance r from a.',
    'metrics.balls.ex.title': '1D Case Example',
    'metrics.balls.ex.desc': 'In the 1D real number line, an open ball is simply an open interval.',
    'metrics.balls.viz.title': 'The Shape-Shifting Ball',
    'metrics.balls.viz.subtitle': 'Adjust the radius and change the metric to see the geometry of an open ball mutate in a 2D plane.',

    // Open Sets
    'nav.metrics.open': '3. Open Sets & Interiors',
    'metrics.open.hero.title': 'The Intuition of Breathing Room',
    'metrics.open.hero.subtitle': 'A set is open if it has no hard skin. Metaphorically, every point inside has enough "breathing room" to inflate a tiny ball that remains entirely trapped inside the set.',
    'metrics.open.def.title': 'Defining Openness',
    'metrics.open.def.intro': 'A subset A is open if every point has a safety radius around it.',
    'metrics.open.prop.title': 'Stability & The Infinite Trap',
    'metrics.open.warn.title': 'The Infinite Intersection Trap',
    'metrics.open.warn.desc': 'You CANNOT take an infinite intersection of open sets and expect it to remain open. Shrinking intervals can collapse into a single point.',
    'metrics.open.interior.title': 'The Interior of a Set',
    'metrics.open.interior.desc': 'The interior is the collection of all points that possess breathing room. A set is open if and only if it equals its interior.',
    'metrics.open.viz.title': 'The Breathing Room Test',
    'metrics.open.viz.subtitle': 'Toggle between an Open and Closed square. Move your probe to see if you can find a point with zero breathing room.',

    // Closed Sets
    'nav.metrics.closed': '4. Closed Sets & Adherence',
    'metrics.closed.hero.title': 'The Skin of the Space',
    'metrics.closed.hero.subtitle': 'If open sets have no skin, closed sets include their entire boundary. They are the shapes that "trap" all their limits—you cannot walk infinitely close to the edge and suddenly fall out.',
    'metrics.closed.def.title': 'Closed Sets & Infinite Traps',
    'metrics.closed.def.intro': 'A subset F is closed if its complement is open. While finite unions are safe, the infinite union of closed sets can break the property.',
    'metrics.closed.warn.title': 'The Infinite Union Trap',
    'metrics.closed.warn.desc': 'You CANNOT take an infinite union of closed sets and expect it to remain closed. A classic example is the union of [1/n, 1] resulting in ]0, 1].',
    'metrics.closed.adh.title': 'Adherence and Closure',
    'metrics.closed.adh.intro': 'A point is adherent to a set if every neighborhood of that point touches the set. The collection of all such points forms the Closure.',
    'metrics.closed.seq.title': 'Sequential Characterization',
    'metrics.closed.seq.desc': 'In metric spaces, a point is in the closure if and only if there is a sequence inside the set that converges to it. This is the ultimate test of belonging.',
    'metrics.closed.viz.title': 'The Sequential Sniper',
    'metrics.closed.viz.subtitle': 'Drag the target point "a" and attempt to hit it with a sequence (xₙ) starting from inside the set A.',

    // Neighborhoods & Separability
    'nav.metrics.neigh': '5. Neighborhoods & Separability',
    'metrics.neigh.hero.title': 'Local Environments and Skeletons',
    'metrics.neigh.hero.subtitle': 'While open sets describe the global map, sometimes we only care about the immediate surroundings of a point. We explore the "building blocks" of space and the hidden countable skeletons that hold everything together.',
    'metrics.neigh.def.title': 'Neighborhoods & Interiors',
    'metrics.neigh.def.intro': 'A set is a neighborhood if it is "thick enough" to swallow an open ball around a point.',
    'metrics.neigh.q.title': 'Counter-Intuitive Fact: The Empty Interior of ℚ',
    'metrics.neigh.q.desc': 'Even though there are infinite fractions, you can NEVER draw a valid open ball made entirely of fractions. Irrationals will always sneak in!',
    'metrics.neigh.base.title': 'Bases: The Building Blocks',
    'metrics.neigh.base.desc': 'A collection is a base if every open set can be built by taking unions of its elements. In metric spaces, open balls are the ultimate base.',
    'metrics.neigh.sep.title': 'Separable Spaces',
    'metrics.neigh.sep.desc': 'A space is separable if it has a countable dense set—a microscopic skeleton that touches every part of the universe.',
    'metrics.neigh.viz.title': 'The Density Zoom',
    'metrics.neigh.viz.subtitle': 'Zoom in on the irrational number √2. Notice how rational fractions dynamically appear to fill every gap, proving that ℚ is dense in ℝ.',

    // Sequences & Adherence
    'nav.metrics.seq': '6. Sequences & Adherence',
    'metrics.seq.hero.title': 'The Intuition of Infinite Journeys',
    'metrics.seq.hero.subtitle': 'Sequences are like infinite journeys through a space. Convergence is reaching a permanent destination; a Value of Adherence is a place you visit infinitely many times.',
    'metrics.seq.def.title': 'Convergence vs. Adherence',
    'metrics.seq.def.conv': 'Definition 12: Convergence',
    'metrics.seq.def.conv_desc': 'Eventually, past some index, ALL future terms are trapped close to the limit.',
    'metrics.seq.def.adh': 'Definition 13: Value of Adherence',
    'metrics.seq.def.adh_desc': 'No matter how far you look, you will ALWAYS find another term that dips close to this point.',
    'metrics.seq.sub.title': 'Subsequences & The Grand Link',
    'metrics.seq.sub.desc': 'A subsequence is formed by picking terms without changing their order. It allows us to extract order from chaotic sequences.',
    'metrics.seq.trap.title': 'Anomalies and Traps',
    'metrics.seq.trap.osc': 'Multiple Values (Divergence)',
    'metrics.seq.trap.single': 'The Single Adherence Trap',
    'metrics.seq.viz.title': 'The Subsequence Extractor',
    'metrics.seq.viz.subtitle': 'Choose a sequence and extract its "even" subsequence to discover hidden convergence.',

    // Continuity
    'nav.metrics.continuity': '7. Continuity: Local to Lipschitz',
    'metrics.cont.hero.title': 'The Hierarchy of Smoothness',
    'metrics.cont.hero.subtitle': 'In metric spaces, continuity is all about bounding the error. If you restrict how much the input changes, can you guarantee the output won\'t jump wildly?',
    'metrics.cont.def.title': 'Local vs. Uniform Continuity',
    'metrics.cont.def.local': 'Proposition 10: Local Continuity',
    'metrics.cont.def.uniform': 'Definition 15: Uniform Continuity',
    'metrics.cont.def.uniform_desc': 'A single restriction rule works everywhere simultaneously. The safety margin alpha depends ONLY on epsilon, not on your location.',
    'metrics.cont.def.lipschitz': 'Definition 16: Lipschitz Continuity',
    'metrics.cont.def.lipschitz_desc': 'The function\'s "speed" is strictly capped by a constant ratio. It is the gold standard of stability.',
    'metrics.cont.viz.title': 'The ε-α Sliding Box',
    'metrics.cont.viz.subtitle': 'Drag the box along the curve. If the curve stays inside the left/right exits without breaking the top/bottom, it is uniformly continuous for this α.',

    // Compactness I
    'nav.metrics.compact': '8. Sequential Compactness',
    'metrics.compact.hero.title': 'The Ultimate Good Behavior',
    'metrics.compact.hero.subtitle': 'Compactness is the topological version of being finite. In a compact space, you cannot stretch to infinity or fall into holes. Every infinite journey is forced to clump up somewhere inside.',
    'metrics.compact.seq.title': 'The Sequential Characterization',
    'metrics.compact.seq.bw': 'Theorem 1: Bolzano-Weierstrass Property',
    'metrics.compact.seq.desc': 'A set A is compact if and only if EVERY sequence in A has a value of adherence in A. Order is always hidden within infinite chaos.',
    'metrics.compact.rules.title': 'The Rules of Compactness',
    'metrics.compact.rules.cb': 'Compact implies Closed and Bounded',
    'metrics.compact.rules.cb_desc': 'Compact sets have no missing boundaries and do not stretch to infinity. Note: The reverse is generally false!',
    'metrics.compact.rules.sub': 'Closed Subsets',
    'metrics.compact.rules.sub_desc': 'A closed shape inside a compact universe is always compact.',
    'metrics.compact.heine.title': 'The Magic of ℝⁿ (Heine-Borel)',
    'metrics.compact.heine.desc': 'In Euclidean space, "Closed + Bounded" is exactly equivalent to being compact. This makes calculus in ℝⁿ very predictable.',
    'metrics.compact.viz.title': 'The Infinite Particle Trap',
    'metrics.compact.viz.subtitle': 'Drop 500 particles into a bounded box. Notice how they are mathematically forced to cluster, forming a value of adherence.',

    // Compactness II
    'nav.metrics.compact2': '9. Continuous Images & Heine',
    'metrics.compact2.hero.title': 'The Power of Preservation',
    'metrics.compact2.hero.subtitle': 'Continuous functions map points without tearing the fabric of space. Because they preserve proximity, they perfectly translate compactness from one universe to another.',
    'metrics.compact2.img.title': 'Continuous Images',
    'metrics.compact2.img.desc': 'If you start with a compact domain, the output is mathematically guaranteed to be safe, bounded, and predictable.',
    'metrics.compact2.trap.title': 'The Inverse Image Trap',
    'metrics.compact2.trap.desc': 'While direct images preserve compactness, inverse images do not. A bounded output doesn\'t mean the input wasn\'t stretching to infinity.',
    'metrics.compact2.extrema.title': 'The Extreme Value Theorem',
    'metrics.compact2.heine.title': 'Heine\'s Theorem',
    'metrics.compact2.heine.desc': 'A continuous function on a compact space is automatically uniformly continuous. Compactness "tames" the function\'s growth.',
    'metrics.compact2.viz.title': 'The Extrema Finder',
    'metrics.compact2.viz.subtitle': 'Toggle between a compact and non-compact domain to see why a continuous function is only guaranteed to reach its bounds on compact sets.',

    // Completeness
    'nav.metrics.complete': '10. Completeness & Fixed Points',
    'metrics.complete.hero.title': 'Completeness & Fixed Points',
    'metrics.complete.hero.subtitle': 'A complete space is a universe with no microscopic holes. In such a perfect environment, any sequence that looks like it is converging mathematically MUST converge. This guarantees the existence of stable fixed points.',
    'metrics.complete.cauchy.title': 'Cauchy Sequences',
    'metrics.complete.cauchy.desc': 'A sequence is Cauchy if its terms eventually get arbitrarily close to EACH OTHER. In a complete space, this is enough to guarantee a limit.',
    'metrics.complete.def.title': 'Complete Spaces',
    'metrics.complete.def.desc': 'A space is complete if every Cauchy sequence converges. A perfect universe for analysis.',
    'metrics.complete.fixed.title': 'The Picard-Banach Fixed-Point Theorem',
    'metrics.complete.fixed.desc': 'A contractive function in a complete space is an attractor: all paths lead to a unique, stable fixed point.',
    'metrics.complete.viz.title': 'The Picard-Banach Attractor',
    'metrics.complete.viz.subtitle': 'Pick a starting point and iterate the function f(x) = cos(x). Watch the cobweb plot spiral into the unique fixed point.',
    'nav.metrics.td1': 'TD1: Discrete Distance',
    
    // TD1 Exercises
    'td1.title': 'Tutorial Session 1',
    'td1.subtitle': 'Metric Spaces & Topology',
    'td1.ex1.title': 'The Discrete Distance',
    'td1.ex1.stmt': 'Let E be a non-empty set and d a mapping defined by:',
    'td1.ex1.q1': '1. Show that d is a distance on E.',
    'td1.ex1.q2': '2. Specify the open and closed sets of (E, d).',
    'td1.ex1.res1.title': '1. Proof that d is a distance',
    'td1.ex1.res1.intro': 'We must verify the three axioms of a distance for all (x, y, z) ∈ E³.',
    'td1.ex1.res1.sep': 'Separation:',
    'td1.ex1.res1.sep_desc': 'By definition, d(x, y) = 0 ⟺ x = y.',
    'td1.ex1.res1.sym': 'Symmetry:',
    'td1.ex1.res1.sym_desc1': 'If x = y, d(x, y) = 0 = d(y, x).',
    'td1.ex1.res1.sym_desc2': 'If x ≠ y, y ≠ x ⟹ d(x, y) = 1 = d(y, x).',
    'td1.ex1.res1.tri': 'Triangle Inequality:',
    'td1.ex1.res1.tri_cas1': 'Case 1: x = z.',
    'td1.ex1.res1.tri_cas1_desc': 'd(x, z) = 0. Since the image of d is {0, 1}, d(x, y) + d(y, z) ≥ 0.',
    'td1.ex1.res1.tri_cas2': 'Case 2: x ≠ z.',
    'td1.ex1.res1.tri_cas2_desc1': 'd(x, z) = 1. Since x ≠ z, y cannot be simultaneously equal to x and z.',
    'td1.ex1.res1.tri_cas2_desc2': 'Thus, either x ≠ y or y ≠ z. This implies max(d(x, y), d(y, z)) = 1.',
    'td1.ex1.res1.tri_cas2_desc3': 'Consequently, d(x, y) + d(y, z) ≥ 1 = d(x, z).',
    'td1.ex1.res1.conc': 'Conclusion: d is a distance on E (called the discrete distance).',
    'td1.ex1.res2.title': '2. Determination of open and closed sets of (E, d)',
    'td1.ex1.res2.open': 'Open Sets:',
    'td1.ex1.res2.open_desc1': 'Let x ∈ E. Consider the open ball with center x and radius r = 1/2:',
    'td1.ex1.res2.open_desc2': 'The only point at distance < 1/2 from x is x itself. Thus, every singleton {x} is an open set.',
    'td1.ex1.res2.open_desc3': 'Since any subset A is the union of its singletons, and any union of open sets is open:',
    'td1.ex1.res2.open_conc': 'Conclusion: Every subset A ⊂ E is open. The set of open sets is P(E).',
    'td1.ex1.res2.closed': 'Closed Sets:',
    'td1.ex1.res2.closed_desc': 'A set is closed if its complement is open. Since every set is open, every complement is open.',
    'td1.ex1.res2.closed_conc': 'Conclusion: Every subset F ⊂ E is closed. The set of closed sets is P(E).',
    'td1.ex1.res2.final': 'General Conclusion: The topology induced by the discrete distance is the discrete topology. All subsets are both open and closed.',

    'td1.ex2.title': 'A Non-Complete Distance on ℝ',
    'td1.ex2.stmt': 'Let δ be the mapping defined on ℝ² by:',
    'td1.ex2.q1': 'Show that δ is a distance on ℝ.',
    'td1.ex2.q2_1': 'Let',
    'td1.ex2.q2_2': 'Show that',
    'td1.ex2.q2_3': 'is a Cauchy sequence for',
    'td1.ex2.q3_1': 'Does',
    'td1.ex2.q3_2': 'converge in',
    'td1.ex2.q3_3': 'What can be said about',
    'td1.ex2.viz.title': 'Cauchy Sequence Visualization',
    'td1.ex2.viz.subtitle_1': 'Observe how',
    'td1.ex2.viz.subtitle_2': 'behaves under the distance',
    'td1.ex2.viz.limit': 'Limit f(l) = 1 (Unreachable)',
    'td1.ex2.viz.paradox': 'The Distance Paradox',
    'td1.ex2.viz.paradox_desc_1': 'Although',
    'td1.ex2.viz.paradox_desc_2': 'moves to infinity in the standard sense, the image',
    'td1.ex2.viz.paradox_desc_3': 'clusters against the limit 1. The gap between terms becomes arbitrarily small: it is a Cauchy sequence.',
    'td1.ex2.viz.noncomp': 'Non-Completeness',
    'td1.ex2.viz.noncomp_desc_1': 'The sequence "wants" to converge to a point',
    'td1.ex2.viz.noncomp_desc_2': 'such that',
    'td1.ex2.viz.noncomp_desc_3': 'But the equation has no solution in ℝ. The limit is "outside the space".',
    'td1.ex2.viz.terms': 'Terms:',
    'td1.ex2.res1.title': '1. Proof that δ is a distance on ℝ',
    'td1.ex2.res1.intro': 'Let f(t) = t / (1+|t|). Then δ(x, y) = |f(x) - f(y)|.',
    'td1.ex2.res1.sep': 'Separation: f is strictly increasing, hence injective. f(x)=f(y) ⟹ x=y.',
    'td1.ex2.res1.tri': 'Triangle Inequality: Derived from the standard absolute value on ℝ.',
    'td1.ex2.res2.title': '2. Cauchy sequence for δ',
    'td1.ex2.res2.desc': 'As n ⟶ ∞, f(n) ⟶ 1. The sequence (f(x_n)) converges in (ℝ, |.|), so it is Cauchy.',
    'td1.ex2.res3.title': '3. Convergence and Completeness',
    'td1.ex2.res3.abs': 'Suppose x_n ⟶ l. Then f(l) = lim f(n) = 1.',
    'td1.ex2.res3.abs2': 'Solving f(l)=1 leads to 0=1 (if l≥0) or 2l=1 (if l<0, impossible). No solution exists in ℝ.',
    'td1.ex2.res3.conc': 'Conclusion: (ℝ, δ) is not complete as it has a Cauchy sequence that does not converge.',
    
    'td1.ex3.title': 'Properties of the Metric Space (E, d)',
    'td1.ex3.stmt': 'Let E = ]0, +∞[, F = ]0, 2], and (u_n) be the sequence u_n = n. For all x, y ∈ E, we set:',
    'td1.ex3.q1': '1. Show that d is a distance on E.',
    'td1.ex3.q2a': '2.a Show that F is closed for d.',
    'td1.ex3.q2b': '2.b Show that F is not bounded for d.',
    'td1.ex3.q3a': '3.a Verify that d(u_n, u_{n+p}) ≤ 1/n for all n, p ≥ 1.',
    'td1.ex3.q3b': '3.b Deduce that (u_n) is a Cauchy sequence in (E, d).',
    'td1.ex3.q4': '4. Show that (E, d) is not complete.',
    'td1.ex3.res1.title': '1. Proof that d is a distance',
    'td1.ex3.res2.title': '2. Study of the subset F',
    'td1.ex3.res2.a_title': '2.a F is closed for d:',
    'td1.ex3.res2.a_desc': 'Let (x_n) be a sequence in F converging to l ∈ E. Then 1/x_n ⟶ 1/l. Since x_n ≤ 2, 1/x_n ≥ 1/2. By the limit law, 1/l ≥ 1/2, so l ≤ 2. Thus l ∈ F.',
    'td1.ex3.res2.b_title': '2.b F is not bounded for d:',
    'td1.ex3.res2.b_desc': 'Consider v_n = 1/n ∈ F. Let y = 1 ∈ F. Then d(v_n, y) = |n - 1|, which tends to infinity.',
    'td1.ex3.res3.title': '3. Cauchy sequence (u_n)',
    'td1.ex3.res4.title': '4. Non-completeness of (E, d)',
    'td1.ex3.res4.desc': 'Suppose u_n ⟶ l ∈ E. Then d(u_n, l) ⟶ 0 ⟹ 1/l = lim 1/n = 0. No such l exists in E.',
    
    'td1.ex4.title': 'Non-Closed Sets of ℝ',
    'td1.ex4.stmt': 'Show that the following sets are not closed in ℝ:',
    'td1.ex4.res.A_title': '1. Proof for Set A:',
    'td1.ex4.res.A_desc': 'The subsequence of even terms u_{2k} = 1 + 1/2k converges to 1. However, 1 ∉ A. By sequential characterization, A is not closed.',
    'td1.ex4.res.B_title': '2. Proof for Set B:',
    'td1.ex4.res.B_desc': 'The sequence v_n = 2/n converges to 0. Since 0 ∉ B, the set B is not closed.',
    'td1.ex4.case_pair': 'If n is even',
    'td1.ex4.case_impair': 'If n is odd',
    'td1.ex4.impossible': 'Impossible',
    
    'td1.ex5.title': 'Topological Analysis of a Subset of ℝ',
    'td1.ex5.stmt': 'Determine with precision the basic and derived topological sets for A. Which one is compact?',
    'td1.ex5.res.adh': 'Adherence: The union of closures. Note that 0 is the limit of 1/k and is included.',
    'td1.ex5.res.int': 'Interior: Only the open interval ]1, 2[ survives. Discrete and rational points have empty interiors.',
    'td1.ex5.res.comp': 'Compactness Analysis: In ℝ, compact ⟺ closed and bounded. Only adh(A) and adh(int(A)) satisfy both.',
    
    'td1.ex6.title': 'Subsets of the Real Plane',
    'td1.ex6.stmt': 'Analyze A1 and A2. Are they open or closed? Determine their interior, closure, and compactness.',
    'td1.ex6.res.A1': 'A1 is open (inverse image of ]1, +∞[ via x²y²). It is not bounded, so not compact.',
    'td1.ex6.res.A2': 'A2 is closed (intersection of closed sphere and half-plane). It is bounded, so it is compact.',
    
    'td1.ex7.title': 'Intersections and Closures',
    'td1.ex7.stmt': 'Let A be open and B any set. Prove the intersection properties.',
    'td1.ex7.res1': '1. Inclusion: Use the fact that A is a neighborhood for its points. Any neighborhood of x ∈ A ∩ adh(B) intersects A ∩ B.',
    'td1.ex7.res2': '2. Implication: Follows directly from part 1 by taking closures.',
    
    'td1.ex8.title': 'Distances and Separation',
    'td1.ex8.q1': '1. Show that d(x, F) = 0 ⟺ x ∈ F for a closed set F.',
    'td1.ex8.q2': '2. Prove that disjoint closed sets can be separated by disjoint open sets.',
    'td1.ex8.res2.desc': 'Use the continuous function f(x) = d(x, F) - d(x, G) to construct the open sets U and V.',
    
    'td1.ex9.title': 'A Norm on C¹([0, 1])',
    'td1.ex9.q1': '1. Show that N is a Euclidean norm.',
    'td1.ex9.q2': '2. Prove the inequalities relating N and the infinity norm.',
    'td1.ex9.res3': '3. Non-equivalence: xⁿ remains bounded by 1 in the infinity norm but its derivative energy explodes.',
    
    'td1.ex10.title': 'Topological Properties of Subspaces',
    'td1.ex10.q1': '1. Show that the closure of a subspace is a subspace.',
    'td1.ex10.q3': '3. Show that a subspace with an interior point is the whole space.',
    'td1.ex10.res4': '4. Application: The subspace of uniformly continuous functions has an empty interior because x² is continuous but not uniformly so.',
    
    'td1.ex11.title': 'Constancy on an Arc-Connected Set',
    'td1.ex11.res': 'Proof: The image of a connected path in a discrete space {0, 1} must be a singleton.',
    
    'td1.ex12.title': 'Non-Arc-Connectedness of GLn(ℝ)',
    'td1.ex12.res': 'Proof: The determinant is continuous. Any path between det > 0 and det < 0 must hit det = 0, which is outside GLn.',

    // TD1 Visualizers
    'td1.viz.discrete.title': 'Discrete Distance Simulator',
    'td1.viz.discrete.subtitle': 'Move the points to observe the value jump.',
    'td1.viz.discrete.euclidean': 'Euclidean',
    'td1.viz.discrete.discrete': 'Discrete',
    'td1.viz.discrete.move': 'MOVE THE POINTS',
    'td1.viz.discrete.rule': 'Decision Rule',
    'td1.viz.discrete.rule_same': 'The points are identical: the distance vanishes instantly.',
    'td1.viz.discrete.rule_diff': 'As soon as points differ, the distance jumps to 1, regardless of physical gap.',
    'td1.viz.discrete.info1': 'Unlike standard distance, discrete distance has no notion of "near" or "far".',
    'td1.viz.discrete.info2': 'Every singleton is open here because it equals a ball of radius 1/2.',
    'td1.viz.discrete.info3': 'This is the finest topology possible: every subset is open.',

    'td1.viz.dist_func.title': 'Space Distortion',
    'td1.viz.dist_func.subtitle': 'Visualize how the distance "stretches" the neighborhood of 0 and "crushes" infinity.',
    'td1.viz.dist_func.standard': 'Standard Real Space',
    'td1.viz.dist_func.inverse': 'Inverse Metric Space',
    'td1.viz.dist_func.pos': 'Position',
    'td1.viz.dist_func.neigh_0': 'The Neighborhood of 0',
    'td1.viz.dist_func.neigh_0_desc': 'As x → 0, its position in metric space escapes to infinity. The neighborhood of 0 is "stretched" infinitely: ]0, 2] is not bounded.',
    'td1.viz.dist_func.inf_crush': 'Crushed Infinity',
    'td1.viz.dist_func.inf_crush_desc': 'As x → +∞, its metric position clusters towards 0. A sequence tending to infinity in the standard sense becomes a Cauchy sequence "wanting" to converge to a non-existent point (0).',

    'td1.viz.set_conv.title': 'Closure Failure: Convergence Outside the Set',
    'td1.viz.set_conv.subtitle': 'Visualize how a sequence from a set converges to a "forbidden" point.',
    'td1.viz.set_conv.set_a': 'Set A',
    'td1.viz.set_conv.set_b': 'Set B',
    'td1.viz.set_conv.limit': 'Limit',
    'td1.viz.set_conv.argument': 'The Sequential Argument',
    'td1.viz.set_conv.arg_a': 'Blue points (even indices) cluster against the red bar (1). Yet, 1 is never reached. Since the set does not contain this accumulation point, it is not closed.',
    'td1.viz.set_conv.arg_b': 'Green points approach 0 without ever reaching it (since 1/n > 0). The limit 0 is "right next to" the set but not part of it.',
    'td1.viz.set_conv.adherence': 'Adherence',
    'td1.viz.set_conv.verdict': 'Verdict',
    'td1.viz.set_conv.not_closed': 'Not Closed',

    'td1.viz.set_topo.title': 'Mapping of Set A',
    'td1.viz.set_topo.subtitle': 'Visualize the different components and their topological nature.',
    'td1.viz.set_topo.interior': 'Interior',
    'td1.viz.set_topo.adherence': 'Adherence',
    'td1.viz.set_topo.isolated': 'Isolated Points',
    'td1.viz.set_topo.isolated_desc': 'Points 1/k are isolated. They have no neighbors in A, so their interior is empty.',
    'td1.viz.set_topo.density': 'Density',
    'td1.viz.set_topo.density_desc': 'Rationals in [2, 3[ are dense: their closure "plugs the holes" to form the complete interval [2, 3].',
    'td1.viz.set_topo.accumulation': 'Accumulation Point',
    'td1.viz.set_topo.accumulation_desc': '0 is not in A, but it is the limit of 1/k. It therefore belongs to the adherence.',
    'td1.viz.set_topo.int_desc': 'The interior is the open interval ]1, 2[',
    'td1.viz.set_topo.adh_desc': 'The adherence contains the closed segment [1, 3]',

    'td1.viz.r2_topo.title': 'Subsets Explorer of R²',
    'td1.viz.r2_topo.subtitle': 'Visualize the shape and topological nature of the studied parts.',
    'td1.viz.r2_topo.set_a1': 'Set A₁',
    'td1.viz.r2_topo.set_a2': 'Set A₂',
    'td1.viz.r2_topo.open': 'Open',
    'td1.viz.r2_topo.closed': 'Closed',
    'td1.viz.r2_topo.bounded': 'Bounded',
    'td1.viz.r2_topo.unbounded': 'Unbounded',
    'td1.viz.r2_topo.analysis_title': 'Interior / Adherence Analysis',
    'td1.viz.r2_topo.analysis_a1': 'The set is "thick" everywhere: you can place a small ball without leaving the blue zone. The adherence would add the boundary curve.',
    'td1.viz.r2_topo.analysis_a2': 'The set is a "wire" with no thickness. Any ball centered on the semi-circle inevitably overflows into the void. Its interior is empty.',
    'td1.viz.r2_topo.verdict_title': 'Compactness Verdict',
    'td1.viz.r2_topo.verdict_a1': 'The horns of the hyperbola extend to infinity (towards ±∞). The set is neither closed (lacks its boundary) nor bounded. Verdict: Not Compact.',
    'td1.viz.r2_topo.verdict_a2': 'The semi-circle contains all its limit points and fits in a square of side 2. Verdict: Compact.',

    'td1.viz.intersect.title': 'Intersections & Adherences Dynamics',
    'td1.viz.intersect.subtitle': 'Observe the impact of the openness of A on the adherence of its intersection with B.',
    'td1.viz.intersect.power_title': 'The Power of Openness',
    'td1.viz.intersect.power_desc': 'Since A is open, every point x ∈ A has a small disk of "neighbors" entirely contained in A. If x touches B (adherence), this disk necessarily touches B, so it touches A ∩ B.',
    'td1.viz.intersect.cons_title': 'Logical Consequence',
    'td1.viz.intersect.cons_desc': 'If A ∩ B is empty, then A cannot even touch the boundary of B. Any "collision" with the adherence would imply a collision with the set itself.',
    'td1.viz.intersect.sep_neigh': 'Separation neighborhood',

    'td1.viz.sep.title': 'Separation of Disjoint Closed Sets',
    'td1.viz.sep.subtitle': 'Visualize how distance creates open separation zones.',
    'td1.viz.sep.adjust': 'Adjust gap',
    'td1.viz.sep.zone_u': 'Open Zone U',
    'td1.viz.sep.zone_v': 'Open Zone V',
    'td1.viz.sep.decision': 'Decision boundary',
    'td1.viz.sep.buffer_title': 'The safety buffer',
    'td1.viz.sep.buffer_desc': 'Since F and G are closed and disjoint, the distance from a point in F to the set G is strictly positive. We can therefore always slide a "bubble" around each set.',
    'td1.viz.sep.normal_title': 'Normal Space',
    'td1.viz.sep.normal_desc': 'This construction shows that metric spaces are "normal": any pair of disjoint closed sets can be separated by disjoint open sets.',

    'td1.viz.norm.title': 'Euclidean Norm Explosion',
    'td1.viz.norm.subtitle': 'Observe why N and ||.||∞ are not equivalent.',
    'td1.viz.norm.adjust': 'Adjust exponent n',
    'td1.viz.norm.function': 'Function',
    'td1.viz.norm.stable_title': 'Uniform Stability',
    'td1.viz.norm.stable_desc': 'For all n, the maximum value remains 1. In the sense of the infinite norm, all these functions are at the same "distance" from the zero function.',
    'td1.viz.norm.energy_title': 'Derivative Energy',
    'td1.viz.norm.energy_desc': 'However, the slope becomes vertical near 1. The integral of f\'² explodes: the Euclidean "distance" N(f_n) tends to infinity. The two worlds diverge.',

    'td1.viz.sub_int.title': 'Interior of a Vector Subspace',
    'td1.viz.sub_int.subtitle': 'Why a proper subspace necessarily has an empty interior.',
    'td1.viz.sub_int.proper': 'Proper Subspace',
    'td1.viz.sub_int.interior': 'Interior Point',
    'td1.viz.sub_int.state_empty': 'State: Empty Interior',
    'td1.viz.sub_int.state_empty_desc': 'F is a "plane" or "line" without thickness in E.',
    'td1.viz.sub_int.state_fill': 'State: F = E',
    'td1.viz.sub_int.state_fill_desc': 'By homothety, F "inflates" until it fills the entire space.',
    'td1.viz.sub_int.homothety_title': 'Invariance by Homothety',
    'td1.viz.sub_int.homothety_desc': 'If a subspace contains a small ball, it contains all its enlarged versions by linearity. An infinitely large ball eventually absorbs any vector x in the space.',
    'td1.viz.sub_int.density_title': 'The Density Hypothesis',
    'td1.viz.sub_int.density_desc': 'For a hyperplane, not being closed means being "holed" everywhere. Its adherence is then forced to be the complete space.',
    'td1.viz.sub_int.vector_x': 'Any vector x',

    'td1.viz.path.title': 'Continuous Arc on a Discrete Space',
    'td1.viz.path.subtitle': 'Visualize why a continuous mapping to {0, 1} is necessarily constant.',
    'td1.viz.path.initial': 'Initial Point x',
    'td1.viz.path.final': 'Final Point y',
    'td1.viz.path.discrete_space': 'Discrete Space',
    'td1.viz.path.part_a': 'Part A',
    'td1.viz.path.jump_impossible': 'Jump Impossible',
    'td1.viz.path.arc_title': 'The Continuous Path',
    'td1.viz.path.arc_desc': 'The arc γ is an unbroken line. Its image by f must also be an unbroken line.',
    'td1.viz.path.bridge_title': 'The Space without "Bridge"',
    'td1.viz.path.bridge_desc': 'To go from 0 to 1, f would have to "jump" or pass through intermediate values. Discrete space has no bridge: the point remains stuck.',

    'td1.viz.gln.title': 'The Barrier of Zero Determinant',
    'td1.viz.gln.subtitle': 'Visualize the impossibility of passing from det > 0 to det < 0 in GL_n.',
    'td1.viz.gln.mat_a': 'Matrix A (det > 0)',
    'td1.viz.gln.mat_b': 'Matrix B (det < 0)',
    'td1.viz.gln.forbidden': 'det = 0',
    'td1.viz.gln.tvi_title': 'IVT in Action',
    'td1.viz.gln.tvi_desc': 'Since the determinant is continuous, to pass from a matrix with positive determinant to one with negative determinant, it is mandatory to pass through a matrix with zero determinant.',
    'td1.viz.gln.fracture_title': 'The Fracture of GLn',
    'td1.viz.gln.fracture_desc': 'However, matrices with zero determinant are not in GL_n. The space is therefore "cut in two" by the void: it cannot be path-connected.',
    'td1.viz.gln.mat_label': 'Matrix',

    'td1.ex3.q3a_title': '3.a Inequality on d(u_n, u_{n+p})',
    'td1.ex3.q3b_title': '3.b Cauchy Sequence',
  },
  FR: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.intro': '1. Introduction',
    'nav.concepts': '2. Concepts de base',
    'nav.bases': '3. Voisinages & Bases',
    'nav.density': '4. Densité & Séparation',
    'nav.induced': '5. Topologie induite',
    'nav.product': '6. Topologie produit',
    'nav.continuity': '7. Continuité & Limites',
    'nav.compact': '8. Espaces compacts',
    'nav.locallyCompact': '9. Localement compact',
    'nav.connected': '10. Espaces connexes',
    'nav.pathConnected': '11. Connexité par arcs',
    'nav.curriculum': 'Programme du cours',
    'nav.comingSoon': 'Plus de sujets à venir.',
    
    // Landing Page
    'landing.title': 'Maîtrisez la Géométrie de la',
    'landing.subtitle': 'Éloignez-vous des distances et des métriques. Plongez dans la beauté abstraite des ensembles, des voisinages et de la continuité.',
    'landing.start': 'Commencer le cours',
    
    // Chapter Summaries
    'chapter.1.desc': 'Comprenez les 3 axiomes fondamentaux, les ensembles ouveils et la définition formelle.',
    'chapter.2.desc': 'Explorez l\'intérieur, l\'adhérence et la frontière, ainsi que les opérations infinies.',
    'chapter.3.desc': 'Comprenez les environnements locaux, les points isolés/d\'accumulation et les briques de base.',
    'chapter.4.desc': 'Explorez les ensembles denses comme les rationnels et la propriété de Hausdorff (séparation).',
    'chapter.5.desc': 'Apprenez comment l\'ouverture est relative à votre "univers" via les sous-espaces.',
    'chapter.6.desc': 'Découvrez comment combiner des espaces et pourquoi les produits infinis ont des règles strictes.',
    'chapter.7.desc': 'Généralisez le calcul infinitésimal. Voyez comment la topologie détecte les discontinuités.',
    'chapter.8.desc': 'Comprenez la propriété de Borel-Lebesgue et pourquoi la compacité est la norme d\'or.',
    'chapter.9.desc': 'Explorez les espaces qui se comportent comme des compacts en zoomant sur chaque point.',
    'chapter.10.desc': 'Comprenez l\'unité topologique via l\'analogie des ciseaux et la conservation des intervalles.',
    'chapter.11.desc': 'Explorez l\'intuition géométrique des chemins et l\'exception de la "Sinusoïde du topologue".',
    
    // Common
    'common.next': 'Leçon suivante',
    'common.chapter': 'Chapitre',
    'common.continue': 'Continuer l\'aventure',
    'common.complete': 'Cours terminé',
    'common.return': 'Retourner à l\'accueil',
    'common.exercice': 'Exercice',
    'common.conclusion': 'Conclusion',
    'common.conclusion_gen': 'Conclusion Générale',
    'common.q': 'Question',
    'common.proof': 'Démonstration',
    'common.solution': 'Solution',

    // Metric Spaces Course
    'nav.metrics.intro': '1. Fondations de la Distance',
    'metrics.hero.title': 'Les fondations de la distance',
    'metrics.hero.subtitle': 'Revenez des ensembles abstraits à une réalité mesurable. Un espace métrique est un univers muni d\'une règle, où chaque point a une distance numérique définie par rapport aux autres.',
    'metrics.def.title': 'Espace métrique & Distance',
    'metrics.def.intro': 'Soit E un ensemble non vide. Une distance (ou métrique) sur E est une fonction d : E × E → ℝ⁺ qui satisfait trois axiomes stricts :',
    'metrics.def.ax1': '1. Séparation / Identité des indiscernables :',
    'metrics.def.ax1_sub': 'La distance entre deux points est nulle si et seulement si ils sont identiques.',
    'metrics.def.ax2': '2. Symétrie :',
    'metrics.def.ax2_sub': 'La distance de A vers B est identique à la distance de B vers A.',
    'metrics.def.ax3': '3. Inégalité triangulaire :',
    'metrics.def.ax3_sub': 'Le chemin direct est toujours le plus court. Faire un détour par un troisième point sera égal ou supérieur à la distance directe.',
    'metrics.ex.title': 'Exemples fondamentaux',
    'metrics.viz.title': 'La forme de la distance',
    'metrics.viz.subtitle': 'Faites glisser les points A, B et C pour vérifier l\'inégalité triangulaire à travers différents univers mathématiques.',

    // Balls and Spheres
    'nav.metrics.balls': '2. Boules et Sphères',
    'metrics.balls.hero.title': 'La géométrie des boules et sphères',
    'metrics.balls.hero.subtitle': 'Dans la géométrie quotidienne, une « boule » est ronde. Pourtant, dans les espaces métriques, sa forme est dictée par la règle de calcul choisie. Selon la métrique, une boule peut ressembler à un cercle, un losange ou un carré.',
    'metrics.balls.def.title': 'Définitions formelles',
    'metrics.balls.def.intro': 'Soit (E, d) un espace métrique, a ∈ E un centre et r > 0 un rayon réel.',
    'metrics.balls.def.open': '1. Boule ouverte :',
    'metrics.balls.def.open_sub': 'L\'ensemble des points dont la distance à a est strictement inférieure à r.',
    'metrics.balls.def.closed': '2. Boule fermée :',
    'metrics.balls.def.closed_sub': 'L\'ensemble des points à une distance inférieure ou égale à r de a.',
    'metrics.balls.def.sphere': '3. Sphère :',
    'metrics.balls.def.sphere_sub': 'L\'ensemble des points situés exactement à une distance r de a.',
    'metrics.balls.ex.title': 'Exemple en 1D',
    'metrics.balls.ex.desc': 'Sur la droite réelle, une boule ouverte est simplement un intervalle ouvert.',
    'metrics.balls.viz.title': 'La boule métamorphique',
    'metrics.balls.viz.subtitle': 'Ajustez le rayon et changez la métrique pour voir la géométrie d\'une boule ouverte muter dans un plan 2D.',

    // Open Sets
    'nav.metrics.open': '3. Ensembles ouverts & Intérieurs',
    'metrics.open.hero.title': 'L\'intuition de l\'espace vital',
    'metrics.open.hero.subtitle': 'Un ensemble est ouvert s\'il n\'a pas de peau rigide. Métaphoriquement, chaque point à l\'intérieur possède assez d\'« espace vital » pour gonfler une petite boule qui reste entièrement piégée dans l\'ensemble.',
    'metrics.open.def.title': 'Définir l\'ouverture',
    'metrics.open.def.intro': 'Une partie A est ouverte si chaque point possède un rayon de sécurité autour de lui.',
    'metrics.open.prop.title': 'Stabilité & Le piège infini',
    'metrics.open.warn.title': 'Le piège de l\'intersection infinie',
    'metrics.open.warn.desc': 'On ne peut PAS prendre une intersection infinie d\'ouverts et espérer qu\'elle reste ouverte. Des intervalles rétrécissants peuvent s\'effondrer en un point unique.',
    'metrics.open.interior.title': 'L\'Intérieur d\'un ensemble',
    'metrics.open.interior.desc': 'L\'intérieur est la collection de tous les points qui possèdent un espace vital. Un ensemble est ouvert si et seulement si il est égal à son intérieur.',
    'metrics.open.viz.title': 'Le Test de l\'Espace Vital',
    'metrics.open.viz.subtitle': 'Basculez entre un carré ouvert et fermé. Déplacez votre sonde pour voir si vous pouvez trouver un point avec un espace vital nul.',

    // Closed Sets
    'nav.metrics.closed': '4. Ensembles fermés & Adhérence',
    'metrics.closed.hero.title': 'La peau de l\'espace',
    'metrics.closed.hero.subtitle': 'Si les ouverts n\'ont pas de peau, les fermés incluent leur frontière entière. Ce sont les formes qui « piègent » toutes leurs limites — vous ne pouvez pas vous approcher infiniment du bord sans y rester coincé.',
    'metrics.closed.def.title': 'Ensembles fermés & Pièges infinis',
    'metrics.closed.def.intro': 'Un sous-ensemble F est fermé si son complémentaire est ouvert. Alors que les réunions finies sont sûres, la réunion infinie de fermés peut briser cette propriété.',
    'metrics.closed.warn.title': 'Le piège de la réunion infinie',
    'metrics.closed.warn.desc': 'On ne peut PAS prendre une réunion infinie de fermés et espérer qu\'elle reste fermée. Un exemple classique est la réunion des [1/n, 1] qui donne ]0, 1].',
    'metrics.closed.adh.title': 'Adhérence et Fermeture',
    'metrics.closed.adh.intro': 'Un point est adhérent à un ensemble si tout voisinage de ce point rencontre l\'ensemble. La collection de tous ces points forme l\'Adhérence.',
    'metrics.closed.seq.title': 'Caractérisation séquentielle',
    'metrics.closed.seq.desc': 'Dans les espaces métriques, un point est dans l\'adhérence si et seulement s\'il existe une suite de points de l\'ensemble qui converge vers lui.',
    'metrics.closed.viz.title': 'Le Sniper Séquentiel',
    'metrics.closed.viz.subtitle': 'Faites glisser la cible « a » et tentez de l\'atteindre avec une suite (xₙ) issue de l\'intérieur de l\'ensemble A.',

    // Neighborhoods & Separability
    'nav.metrics.neigh': '5. Voisinages & Séparabilité',
    'metrics.neigh.hero.title': 'Environnements locaux et squelettes',
    'metrics.neigh.hero.subtitle': 'Alors que les ouverts décrivent la carte globale, nous ne nous soucions parfois que de l\'entourage immédiat d\'un point. Nous explorons les « briques » de l\'espace et les squelettes dénombrables cachés qui maintiennent l\'ensemble.',
    'metrics.neigh.def.title': 'Voisinages & Intérieurs',
    'metrics.neigh.def.intro': 'Un ensemble est un voisinage s\'il est « assez épais » pour avaler une boule ouverte autour d\'un point.',
    'metrics.neigh.q.title': 'Fait contre-intuitif : l\'intérieur vide de ℚ',
    'metrics.neigh.q.desc': 'Même s\'il existe une infinité de fractions, on ne peut JAMAIS tracer une boule ouverte composée uniquement de fractions. Les irrationnels s\'y glisseront toujours !',
    'metrics.neigh.base.title': 'Bases : les briques de base',
    'metrics.neigh.base.desc': 'Une famille est une base si tout ouvert peut être construit par réunion de ses éléments. Dans les espaces métriques, les boules forment la base ultime.',
    'metrics.neigh.sep.title': 'Espaces séparables',
    'metrics.neigh.sep.desc': 'Un espace est séparable s\'il possède une partie dénombrable dense — un squelette microscopique qui touche chaque recoin de l\'univers.',
    'metrics.neigh.viz.title': 'Le Zoom de Densité',
    'metrics.neigh.viz.subtitle': 'Zoomez sur le nombre irrationnel √2. Notez comment les fractions rationnelles apparaissent dynamiquement pour combler chaque vide, prouvant que ℚ est dense dans ℝ.',

    // Sequences & Adherence
    'nav.metrics.seq': '6. Suites & Adhérence',
    'metrics.seq.hero.title': 'L\'intuition des voyages infinis',
    'metrics.seq.hero.subtitle': 'Les suites sont comme des voyages infinis dans l\'espace. La convergence est l\'atteinte d\'une destination fixe ; une valeur d\'adhérence est un lieu visité une infinité de fois.',
    'metrics.seq.def.title': 'Convergence vs Adhérence',
    'metrics.seq.def.conv': 'Définition 12 : Convergence',
    'metrics.seq.def.conv_desc': 'Finalement, passé un certain rang, TOUS les termes futurs sont piégés près de la limite.',
    'metrics.seq.def.adh': 'Définition 13 : Valeur d\'adhérence',
    'metrics.seq.def.adh_desc': 'Peu importe où vous regardez, vous trouverez TOUJOURS un terme futur qui revient vers ce point.',
    'metrics.seq.sub.title': 'Sous-suites & Le Grand Lien',
    'metrics.seq.sub.desc': 'Une suite extraite est formée en choisissant des termes sans changer leur ordre. Elle permet d\'extraire l\'ordre du chaos.',
    'metrics.seq.trap.title': 'Anomalies et Pièges',
    'metrics.seq.trap.osc': 'Valeurs multiples (Divergence)',
    'metrics.seq.trap.single': 'Le piège de l\'adhérence unique',
    'metrics.seq.viz.title': 'L\'Extracteur de Sous-suite',
    'metrics.seq.viz.subtitle': 'Choisissez une suite et extrayez sa sous-suite « paire » pour découvrir une convergence cachée.',

    // Continuity
    'nav.metrics.continuity': '7. Continuité : du Local au Lipschitz',
    'metrics.cont.hero.title': 'La hiérarchie de la régularité',
    'metrics.cont.hero.subtitle': 'Dans les espaces métriques, la continuité consiste à borner l\'erreur. Si vous restreignez la variation en entrée, pouvez-vous garantir que la sortie ne sautera pas sauvagement ?',
    'metrics.cont.def.title': 'Continuité Locale vs Uniforme',
    'metrics.cont.def.local': 'Proposition 10 : Continuité Locale',
    'metrics.cont.def.uniform': 'Définition 15 : Continuité Uniforme',
    'metrics.cont.def.uniform_desc': 'Une règle unique fonctionne partout simultanément. La marge de sécurité alpha dépend UNIQUEMENT de epsilon.',
    'metrics.cont.def.lipschitz': 'Définition 16 : Applications Lipschitziennes',
    'metrics.cont.def.lipschitz_desc': 'La « vitesse » de la fonction est strictement plafonnée par un rapport constant. C\'est la norme d\'or de la stabilité.',
    'metrics.cont.viz.title': 'La Boîte Coulissante ε-α',
    'metrics.cont.viz.subtitle': 'Faites glisser la boîte le long de la courbe. Si la courbe reste dans les sorties latérales sans casser le haut/bas, elle est uniformément continue pour cet α.',

    // Compactness I
    'nav.metrics.compact': '8. Compacité séquentielle',
    'metrics.compact.hero.title': 'Le comportement idéal',
    'metrics.compact.hero.subtitle': 'La compacité est la version topologique de la finitude. Dans un espace compact, on ne peut pas s\'étendre à l\'infini ni tomber dans des trous. Chaque voyage infini est forcé de s\'agglutiner quelque part.',
    'metrics.compact.seq.title': 'La caractérisation séquentielle',
    'metrics.compact.seq.bw': 'Théorème 1 : Propriété de Bolzano-Weierstrass',
    'metrics.compact.seq.desc': 'Une partie A est compacte si et seulement si TOUTE suite d\'éléments de A admet une valeur d\'adhérence dans A. L\'ordre est toujours caché dans le chaos infini.',
    'metrics.compact.rules.title': 'Les règles de la compacité',
    'metrics.compact.rules.cb': 'Compact implique Fermé et Borné',
    'metrics.compact.rules.cb_desc': 'Les ensembles compacts n\'ont pas de frontières manquantes et ne s\'étendent pas à l\'infini. Note : La réciproque est généralement fausse !',
    'metrics.compact.rules.sub': 'Sous-ensembles fermés',
    'metrics.compact.rules.sub_desc': 'Une forme fermée dans un univers compact est toujours compacte.',
    'metrics.compact.heine.title': 'La magie de ℝⁿ (Heine-Borel)',
    'metrics.compact.heine.desc': 'Dans l\'espace euclidien, « Fermé + Borné » est exactement équivalent à être compact. Cela rend l\'analyse dans ℝⁿ très prévisible.',
    'metrics.compact.viz.title': 'Le Piège à Particules Infini',
    'metrics.compact.viz.subtitle': 'Lâchez 500 particules dans une boîte bornée. Notez comment elles sont mathématiquement forcées de s\'agglutiner, formant une valeur d\'adhérence.',

    // Compactness II
    'nav.metrics.compact2': '9. Images continues & Heine',
    'metrics.compact2.hero.title': 'Le pouvoir de la préservation',
    'metrics.compact2.hero.subtitle': 'Les fonctions continues transportent les points sans déchirer le tissu de l\'espace. Parce qu\'elles préservent la proximité, elles traduisent parfaitement la compacité d\'un univers à l\'autre.',
    'metrics.compact2.img.title': 'Images continues',
    'metrics.compact2.img.desc': 'Si vous partez d\'un domaine compact, la sortie est mathématiquement garantie comme sûre, bornée et prévisible.',
    'metrics.compact2.trap.title': 'Le piège de l\'image réciproque',
    'metrics.compact2.trap.desc': 'Alors que les images directes préservent la compacité, les images réciproques ne le font pas. Une sortie bornée ne signifie pas que l\'entrée ne s\'étendait pas à l\'infini.',
    'metrics.compact2.extrema.title': 'Théorème des Bornes Atteintes',
    'metrics.compact2.heine.title': 'Théorème de Heine',
    'metrics.compact2.heine.desc': 'Une fonction continue sur un espace compact est automatiquement uniformément continue. La compacité « dompte » la croissance de la fonction.',
    'metrics.compact2.viz.title': 'L\'Extracteur d\'Extrema',
    'metrics.compact2.viz.subtitle': 'Basculez entre un domaine compact et non-compact pour voir pourquoi une fonction continue n\'est garantie d\'atteindre ses bornes que sur des ensembles compacts.',

    // Completeness
    'nav.metrics.complete': '10. Complétude & Points Fixes',
    'metrics.complete.hero.title': 'Complétude & Points Fixes',
    'metrics.complete.hero.subtitle': 'Un espace complet est un univers sans trous microscopiques. Dans un tel environnement, toute suite qui semble converger mathématiquement DOIT converger. Cela garantit l\'existence de points fixes stables.',
    'metrics.complete.cauchy.title': 'Suites de Cauchy',
    'metrics.complete.cauchy.desc': 'Une suite est de Cauchy si ses termes finissent par se rapprocher arbitrairement les uns des autres. Dans un espace complet, cela suffit à garantir une limite.',
    'metrics.complete.def.title': 'Espaces Complets',
    'metrics.complete.def.desc': 'Un espace est complet si toute suite de Cauchy y converge. Un univers parfait pour l\'analyse.',
    'metrics.complete.fixed.title': 'Théorème du point fixe de Picard-Banach',
    'metrics.complete.fixed.desc': 'Une fonction contractante dans un espace complet est un attracteur : tous les chemins mènent à un point fixe unique et stable.',
    'metrics.complete.viz.title': 'L\'attracteur de Picard-Banach',
    'metrics.complete.viz.subtitle': 'Choisissez un point de départ et itérez la fonction f(x) = cos(x). Observez le diagramme en toile d\'araignée spiraler vers le point fixe unique.',
    'nav.metrics.td1': 'TD1 : La distance discrète',
    
    // TD1 Exercises
    'td1.title': 'Travaux Dirigés 1',
    'td1.subtitle': 'Espaces Métriques & Topologie',
    'td1.ex1.title': 'La distance discrète',
    'td1.ex1.stmt': 'Soient E un ensemble non vide et d une application définie par :',
    'td1.ex1.q1': '1. Montrer que d est une distance sur E.',
    'td1.ex1.q2': '2. Préciser les ouverts et les fermés de (E, d).',
    'td1.ex1.res1.title': '1. Démonstration que d est une distance',
    'td1.ex1.res1.intro': 'Il faut vérifier les trois axiomes d\'une distance pour tout (x, y, z) ∈ E³.',
    'td1.ex1.res1.sep': 'Séparation :',
    'td1.ex1.res1.sep_desc': 'Par définition, d(x, y) = 0 ⟺ x = y.',
    'td1.ex1.res1.sym': 'Symétrie :',
    'td1.ex1.res1.sym_desc1': 'Si x = y, d(x, y) = 0 = d(y, x).',
    'td1.ex1.res1.sym_desc2': 'Si x ≠ y, y ≠ x ⟹ d(x, y) = 1 = d(y, x).',
    'td1.ex1.res1.tri': 'Inégalité triangulaire :',
    'td1.ex1.res1.tri_cas1': 'Cas 1 : x = z.',
    'td1.ex1.res1.tri_cas1_desc': 'd(x, z) = 0. Puisque l\'image de d est {0, 1}, d(x, y) + d(y, z) ≥ 0.',
    'td1.ex1.res1.tri_cas2': 'Cas 2 : x ≠ z.',
    'td1.ex1.res1.tri_cas2_desc1': 'd(x, z) = 1. Puisque x ≠ z, y ne peut être simultanément égal à x et à z.',
    'td1.ex1.res1.tri_cas2_desc2': 'Donc, soit x ≠ y, soit y ≠ z. Ceci implique que max(d(x, y), d(y, z)) = 1.',
    'td1.ex1.res1.tri_cas2_desc3': 'Par conséquent, d(x, y) + d(y, z) ≥ 1 = d(x, z).',
    'td1.ex1.res1.conc': 'Conclusion : d est une distance sur E (appelée distance discrète).',
    'td1.ex1.res2.title': '2. Détermination des ouverts et des fermés de (E, d)',
    'td1.ex1.res2.open': 'Les ouverts :',
    'td1.ex1.res2.open_desc1': 'Soit x ∈ E. Considérons la boule ouverte de centre x et de rayon r = 1/2 :',
    'td1.ex1.res2.open_desc2': 'Le seul point à distance < 1/2 de x est x lui-même. Donc, tout singleton {x} est un ouvert.',
    'td1.ex1.res2.open_desc3': 'Soit A ⊂ E. On peut écrire A comme la réunion de ses éléments :',
    'td1.ex1.res2.open_conc': 'Conclusion : Toute partie A ⊂ E est un ouvert. L\'ensemble des ouverts est P(E).',
    'td1.ex1.res2.closed': 'Les fermés :',
    'td1.ex1.res2.closed_desc': 'Par définition, F est fermé si son complémentaire est un ouvert. Puisque toute partie est ouverte, tout complémentaire est ouvert.',
    'td1.ex1.res2.closed_conc': 'Conclusion : Toute partie F ⊂ E est un fermé. L\'ensemble des fermés est P(E).',
    'td1.ex1.res2.final': 'Conclusion Générale : La topologie induite par la distance discrète est la topologie discrète. Tous les sous-ensembles sont à la fois ouverts et fermés.',

    'td1.ex2.title': 'Une distance non complète sur ℝ',
    'td1.ex2.stmt': 'Soit δ l\'application définie sur ℝ² par :',
    'td1.ex2.q1': 'Montrer que δ est une distance sur ℝ.',
    'td1.ex2.q2_1': 'Soit',
    'td1.ex2.q2_2': 'Montrer que',
    'td1.ex2.q2_3': 'est une suite de Cauchy pour',
    'td1.ex2.q3_1': 'La suite',
    'td1.ex2.q3_2': 'converge-t-elle dans',
    'td1.ex2.q3_3': 'Que peut-on dire de',
    'td1.ex2.viz.title': 'Visualisation de la Suite de Cauchy',
    'td1.ex2.viz.subtitle_1': 'Observez comment',
    'td1.ex2.viz.subtitle_2': 'se comporte sous la distance',
    'td1.ex2.viz.limit': 'Limite f(l) = 1 (Inatteignable)',
    'td1.ex2.viz.paradox': 'Le paradoxe de la distance',
    'td1.ex2.viz.paradox_desc_1': 'Bien que',
    'td1.ex2.viz.paradox_desc_2': 's\'éloigne à l\'infini au sens usuel, l\'image',
    'td1.ex2.viz.paradox_desc_3': 'se "tasse" contre la barre des 1. L\'écart entre les termes devient arbitrairement petit : c\'est une suite de Cauchy.',
    'td1.ex2.viz.noncomp': 'Non-Complétude',
    'td1.ex2.viz.noncomp_desc_1': 'La suite "veut" converger vers un point',
    'td1.ex2.viz.noncomp_desc_2': 'tel que',
    'td1.ex2.viz.noncomp_desc_3': 'Mais l\'équation n\'a pas de solution dans ℝ. La limite est "hors de l\'espace".',
    'td1.ex2.viz.terms': 'Termes :',
    'td1.ex2.res1.title': '1. Démonstration que δ est une distance sur ℝ',
    'td1.ex2.res1.intro': 'On pose f(t) = t / (1+|t|). Ainsi, δ(x, y) = |f(x) - f(y)|.',
    'td1.ex2.res1.sep': 'Séparation : f est strictement croissante, donc injective. f(x)=f(y) ⟹ x=y.',
    'td1.ex2.res1.tri': 'Inégalité triangulaire : Découle de la valeur absolue usuelle sur ℝ.',
    'td1.ex2.res2.title': '2. Suite de Cauchy pour δ',
    'td1.ex2.res2.desc': 'Quand n ⟶ ∞, f(n) ⟶ 1. La suite (f(x_n)) converge dans (ℝ, |.|), elle est donc de Cauchy.',
    'td1.ex2.res3.title': '3. Convergence et complétude',
    'td1.ex2.res3.abs': 'Supposons x_n ⟶ l. Alors f(l) = lim f(n) = 1.',
    'td1.ex2.res3.abs2': 'La résolution de f(l)=1 mène à 0=1 (si l≥0) ou 2l=1 (si l<0, impossible). Aucune solution réelle.',
    'td1.ex2.res3.conc': 'Conclusion : (ℝ, δ) n\'est pas complet car il possède une suite de Cauchy divergente.',

    'td1.ex3.title': 'Propriétés de l\'espace métrique (E, d)',
    'td1.ex3.stmt': 'Soient E = ]0, +∞[, F = ]0, 2], et (u_n) la suite définie par u_n = n. Pour tous x, y ∈ E, on pose :',
    'td1.ex3.q1': '1. Montrer que d est une distance sur E.',
    'td1.ex3.q2a': '2.a Montrer que la partie F est fermée pour d.',
    'td1.ex3.q2b': '2.b Montrer que F n\'est pas bornée pour d.',
    'td1.ex3.q3a': '3.a Vérifier que d(u_n, u_{n+p}) ≤ 1/n, pour tous n, p ≥ 1.',
    'td1.ex3.q3b': '3.b En déduire que (u_n) est une suite de Cauchy dans (E, d).',
    'td1.ex3.q4': '4. Montrer que l\'espace métrique (E, d) n\'est pas complet.',
    'td1.ex3.res1.title': '1. Démonstration que d est une distance',
    'td1.ex3.res2.title': '2. Étude de la partie F',
    'td1.ex3.res2.a_title': '2.a F est fermée pour d :',
    'td1.ex3.res2.a_desc': 'Soit (x_n) une suite de F convergeant vers l ∈ E. Alors 1/x_n ⟶ 1/l. Comme x_n ≤ 2, 1/x_n ≥ 1/2. Par passage à la limite, 1/l ≥ 1/2, d\'où l ≤ 2 et l ∈ F.',
    'td1.ex3.res2.b_title': '2.b F n\'est pas bornée pour d :',
    'td1.ex3.res2.b_desc': 'Considérons v_n = 1/n ∈ F. Soit y = 1 ∈ F. Alors d(v_n, y) = |n - 1|, qui tend vers l\'infini.',
    'td1.ex3.res3.title': '3. Suite de Cauchy (u_n)',
    'td1.ex3.res4.title': '4. Non complétude de (E, d)',
    'td1.ex3.res4.desc': 'Supposons u_n ⟶ l ∈ E. Alors d(u_n, l) ⟶ 0 ⟹ 1/l = lim 1/n = 0. Or 0 ∉ image(f).',

    'td1.ex4.title': 'Ensembles non fermés de ℝ',
    'td1.ex4.stmt': 'Montrer que les ensembles suivants ne sont pas des fermés de ℝ :',
    'td1.ex4.res.A_title': '1. Démonstration pour l\'ensemble A :',
    'td1.ex4.res.A_desc': 'La sous-suite des termes pairs u_{2k} = 1 + 1/2k converge vers 1. Or 1 ∉ A. Par caractérisation séquentielle, A n\'est pas fermé.',
    'td1.ex4.res.B_title': '2. Démonstration pour l\'ensemble B :',
    'td1.ex4.res.B_desc': 'La suite v_n = 2/n converge vers 0. Comme 0 ∉ B, l\'ensemble B n\'est pas fermé.',
    'td1.ex4.case_pair': 'Si n est pair',
    'td1.ex4.case_impair': 'Si n est impair',
    'td1.ex4.impossible': 'Impossible',

    'td1.ex5.title': 'Analyse topologique d\'une partie de ℝ',
    'td1.ex5.stmt': 'Déterminer avec précision les ensembles topologiques de base et dérivés pour A. Lequel est compact ?',
    'td1.ex5.res.adh': 'Adhérence : Réunion des adhérences. Notez que 0 est limite de 1/k et est inclus.',
    'td1.ex5.res.int': 'Intérieur : Seul l\'intervalle ouvert ]1, 2[ subsiste. Les points isolés et rationnels ont un intérieur vide.',
    'td1.ex5.res.comp': 'Analyse de compacité : Dans ℝ, compact ⟺ fermé et borné. Seuls adh(A) et adh(int(A)) le sont.',

    'td1.ex6.title': 'Sous-ensembles du plan réel',
    'td1.ex6.stmt': 'Analyser A1 et A2. Sont-ils ouverts ou fermés ? Déterminer intérieur, adhérence et compacité.',
    'td1.ex6.res.A1': 'A1 est ouvert (image réciproque de ]1, +∞[ par x²y²). Il est non borné, donc non compact.',
    'td1.ex6.res.A2': 'A2 est fermé (intersection sphère fermée et demi-plan). Il est borné, donc compact.',

    'td1.ex7.title': 'Intersections et adhérences',
    'td1.ex7.stmt': 'Soit A un ouvert et B une partie quelconque. Démontrer les propriétés d\'intersection.',
    'td1.ex7.res1': '1. Inclusion : Utilise le fait que A est un voisinage de ses points. Tout voisinage de x ∈ A ∩ adh(B) rencontre A ∩ B.',
    'td1.ex7.res2': '2. Implication : Découle directement du point 1 par passage à l\'adhérence.',

    'td1.ex8.title': 'Distances et séparation',
    'td1.ex8.q1': '1. Montrer que d(x, F) = 0 ⟺ x ∈ F pour un fermé F.',
    'td1.ex8.q2': '2. Montrer que deux fermés disjoints sont séparés par des ouverts disjoints.',
    'td1.ex8.res2.desc': 'Utiliser la fonction continue f(x) = d(x, F) - d(x, G) pour construire les ouverts U et V.',

    'td1.ex9.title': 'Une norme sur C¹([0, 1])',
    'td1.ex9.q1': '1. Montrer que N est une norme euclidienne.',
    'td1.ex9.q2': '2. Démontrer les inégalités reliant N et la norme infinie.',
    'td1.ex9.res3': '3. Non-équivalence : xⁿ reste bornée par 1 en norme infinie mais son énergie dérivée explose.',

    'td1.ex10.title': 'Propriétés topologiques des s.e.v.',
    'td1.ex10.q1': '1. Montrer que l\'adhérence d\'un s.e.v. est un s.e.v.',
    'td1.ex10.q3': '3. Montrer qu\'un s.e.v. avec un point intérieur est l\'espace entier.',
    'td1.ex10.res4': '4. Application : Le s.e.v. des fonctions uniformément continues est d\'intérieur vide car x² est continue mais pas uniformément.',

    'td1.ex11.title': 'Constance sur un connexe par arcs',
    'td1.ex11.res': 'Démonstration : L\'image d\'un chemin connexe dans un espace discret {0, 1} est nécessairement un singleton.',

    'td1.ex12.title': 'Non-connexité de GLn(ℝ)',
    'td1.ex12.res': 'Démonstration : Le déterminant est continu. Tout chemin entre det > 0 et det < 0 croise det = 0, hors de GLn.',

    // TD1 Visualizers
    'td1.viz.discrete.title': 'Simulateur de Distance Discrète',
    'td1.viz.discrete.subtitle': 'Déplacez les points pour observer le saut de valeur.',
    'td1.viz.discrete.euclidean': 'Euclidienne',
    'td1.viz.discrete.discrete': 'Discrète',
    'td1.viz.discrete.move': 'DÉPLACEZ LES POINTS',
    'td1.viz.discrete.rule': 'Règle de décision',
    'td1.viz.discrete.rule_same': 'Les points sont confondus : la distance s\'annule instantanément.',
    'td1.viz.discrete.rule_diff': 'Dès que les points diffèrent, la distance saute à 1, peu importe l\'écart physique.',
    'td1.viz.discrete.info1': 'Contrairement à la distance usuelle, la distance discrète ne connaît pas la notion de "proche" ou "loin".',
    'td1.viz.discrete.info2': 'Ici, tout singleton est ouvert car il est égal à une boule de rayon 1/2.',
    'td1.viz.discrete.info3': 'C\'est la topologie la plus fine possible : tout sous-ensemble est ouvert.',

    'td1.viz.dist_func.title': 'Distorsion de l\'Espace',
    'td1.viz.dist_func.subtitle': 'Visualisez comment la distance "étire" le voisinage de 0 et "écrase" l\'infini.',
    'td1.viz.dist_func.standard': 'Espace Réel (Standard)',
    'td1.viz.dist_func.inverse': 'Espace Métrique (Inverse)',
    'td1.viz.dist_func.pos': 'Position',
    'td1.viz.dist_func.neigh_0': 'Le voisinage de 0',
    'td1.viz.dist_func.neigh_0_desc': 'Quand x → 0, sa position dans l\'espace métrique s\'enfuit vers l\'infini. Le voisinage de 0 est "étiré" à l\'infini : ]0, 2] n\'est pas borné.',
    'td1.viz.dist_func.inf_crush': 'L\'infini écrasé',
    'td1.viz.dist_func.inf_crush_desc': 'Quand x → +∞, sa position metric se tasse vers 0. Une suite qui tend vers l\'infini au sens usuel devient une suite de Cauchy qui "veut" converger vers un point inexistant (0).',

    'td1.viz.set_conv.title': 'Défaut de Fermeture : Convergence Hors de l\'Ensemble',
    'td1.viz.set_conv.subtitle': 'Visualisez comment une suite d\'un ensemble converge vers un point "interdit".',
    'td1.viz.set_conv.set_a': 'Ensemble A',
    'td1.viz.set_conv.set_b': 'Ensemble B',
    'td1.viz.set_conv.limit': 'Limite',
    'td1.viz.set_conv.argument': 'L\'Argument Séquentiel',
    'td1.viz.set_conv.arg_a': 'Les points bleus (indices pairs) s\'accumulent contre la barre rouge (1). Pourtant, 1 n\'est jamais atteint. Puisque l\'ensemble ne contient pas ce point d\'accumulation, il n\'est pas fermé.',
    'td1.viz.set_conv.arg_b': 'Les points verts s\'approchent de 0 sans jamais l\'atteindre (car 1/n > 0). La limite 0 est "right next to" l\'ensemble mais n\'en fait pas partie.',
    'td1.viz.set_conv.adherence': 'Adhérence',
    'td1.viz.set_conv.verdict': 'Verdict',
    'td1.viz.set_conv.not_closed': 'Non Fermé',

    'td1.viz.set_topo.title': 'Cartographie de l\'Ensemble A',
    'td1.viz.set_topo.subtitle': 'Visualisez les différentes composantes et leur nature topologique.',
    'td1.viz.set_topo.interior': 'Intérieur',
    'td1.viz.set_topo.adherence': 'Adhérence',
    'td1.viz.set_topo.isolated': 'Points Isolés',
    'td1.viz.set_topo.isolated_desc': 'Les points 1/k sont isolés. Ils n\'ont pas de voisins dans A, donc leur intérieur est vide.',
    'td1.viz.set_topo.density': 'Densité',
    'td1.viz.set_topo.density_desc': 'Les rationnels dans [2, 3[ sont denses : leur adhérence "bouche les trous" pour former l\'intervalle complet [2, 3].',
    'td1.viz.set_topo.accumulation': 'Point d\'Accumulation',
    'td1.viz.set_topo.accumulation_desc': '0 n\'est pas dans A, mais c\'est la limite de 1/k. Il appartient donc à l\'adhérence.',
    'td1.viz.set_topo.int_desc': 'L\'intérieur est l\'intervalle ouvert ]1, 2[',
    'td1.viz.set_topo.adh_desc': 'L\'adhérence contient le segment fermé [1, 3]',

    'td1.viz.r2_topo.title': 'Explorateur de Sous-ensembles de R²',
    'td1.viz.r2_topo.subtitle': 'Visualisez la forme et la nature topologique des parties étudiées.',
    'td1.viz.r2_topo.set_a1': 'Ensemble A₁',
    'td1.viz.r2_topo.set_a2': 'Ensemble A₂',
    'td1.viz.r2_topo.open': 'Ouvert',
    'td1.viz.r2_topo.closed': 'Fermé',
    'td1.viz.r2_topo.bounded': 'Borné',
    'td1.viz.r2_topo.unbounded': 'Non Borné',
    'td1.viz.r2_topo.analysis_title': 'Analyse Intérieur / Adhérence',
    'td1.viz.r2_topo.analysis_a1': 'L\'ensemble est "épais" en tout point : vous pouvez placer une petite bille sans sortir de la zone bleue. L\'adhérence rajouterait la courbe frontière.',
    'td1.viz.r2_topo.analysis_a2': 'L\'ensemble est un "fil" sans épaisseur. Toute bille centrée sur le demi-cercle déborde inévitablement dans le vide. Son intérieur est vide.',
    'td1.viz.r2_topo.verdict_title': 'Verdict de Compacité',
    'td1.viz.r2_topo.verdict_a1': 'Les cornes de l\'hyperbole s\'étendent à l\'infini (vers ±∞). L\'ensemble n\'est ni fermé (manque sa frontière), ni borné. Verdict : Non Compact.',
    'td1.viz.r2_topo.verdict_a2': 'Le demi-cercle contient tous ses points limites et tient dans un carré de côté 2. Verdict : Compact.',

    'td1.viz.intersect.title': 'Dynamique des Intersections & Adhérences',
    'td1.viz.intersect.subtitle': 'Observez l\'impact de l\'ouverture de A sur l\'adhérence de son intersection avec B.',
    'td1.viz.intersect.power_title': 'Le Pouvoir de l\'Ouverture',
    'td1.viz.intersect.power_desc': 'Puisque A est ouvert, tout point x ∈ A possède un petit disque de "voisins" entièrement contenus dans A. Si x touche B (adhérence), ce disque touche forcément B, donc il touche A ∩ B.',
    'td1.viz.intersect.cons_title': 'Conséquence Logique',
    'td1.viz.intersect.cons_desc': 'Si A ∩ B est vide, alors A ne peut même pas effleurer la frontière de B. Toute "collision" avec l\'adhérence impliquerait une collision avec l\'ensemble lui-même.',
    'td1.viz.intersect.sep_neigh': 'Voisinage de séparation',

    'td1.viz.sep.title': 'Séparation de Fermés Disjoints',
    'td1.viz.sep.subtitle': 'Visualisez comment la distance crée des zones de séparation ouvertes.',
    'td1.viz.sep.adjust': 'Ajuster l\'écart',
    'td1.viz.sep.zone_u': 'Zone Ouverte U',
    'td1.viz.sep.zone_v': 'Zone Ouverte V',
    'td1.viz.sep.decision': 'Frontière de décision',
    'td1.viz.sep.buffer_title': 'Le tampon de sécurité',
    'td1.viz.sep.buffer_desc': 'Puisque F et G sont fermés et disjoints, la distance d\'un point de F à l\'ensemble G est strictement positive. On peut donc toujours glisser une "bulle" autour de chaque ensemble.',
    'td1.viz.sep.normal_title': 'L\'Espace Normal',
    'td1.viz.sep.normal_desc': 'Cette construction montre que les espaces métriques sont "normaux" : on peut séparer n\'importe quel couple de fermés disjoints par des ouverts disjoints.',

    'td1.viz.norm.title': 'Explosion de la Norme Euclidienne',
    'td1.viz.norm.subtitle': 'Observez pourquoi N et ||.||∞ ne sont pas équivalentes.',
    'td1.viz.norm.adjust': 'Ajuster l\'exposant n',
    'td1.viz.norm.function': 'Fonction',
    'td1.viz.norm.stable_title': 'Stabilité Uniforme',
    'td1.viz.norm.stable_desc': 'Pour tout n, la valeur maximale reste 1. Au sens de la norme infinie, toutes ces fonctions sont à la même "distance" de la fonction nulle.',
    'td1.viz.norm.energy_title': 'L\'énergie de la Dérivée',
    'td1.viz.norm.energy_desc': 'Cependant, la pente devient verticale près de 1. L\'intégrale de f\'² explose : la "distance" euclidienne N(f_n) tend vers l\'infini. Les deux mondes divergent.',

    'td1.viz.sub_int.title': 'L\'Intérieur d\'un Sous-Espace Vectoriel',
    'td1.viz.sub_int.subtitle': 'Pourquoi un s.e.v. propre est forcément d\'intérieur vide.',
    'td1.viz.sub_int.proper': 'S.E.V. Propre',
    'td1.viz.sub_int.interior': 'Point Intérieur',
    'td1.viz.sub_int.state_empty': 'État : Intérieur Vide',
    'td1.viz.sub_int.state_empty_desc': 'F est un "plan" ou une "droite" sans épaisseur dans E.',
    'td1.viz.sub_int.state_fill': 'État : F = E',
    'td1.viz.sub_int.state_fill_desc': 'Par homothétie, F "gonfle" jusqu\'à remplir tout l\'espace.',
    'td1.viz.sub_int.homothety_title': 'Invariance par Homothety',
    'td1.viz.sub_int.homothety_desc': 'Si un s.e.v. contient une petite bille, il contient par linéarité toutes ses versions agrandies. Une bille infiniment grande finit par absorber n\'importe quel vecteur x de l\'espace.',
    'td1.viz.sub_int.density_title': 'L\'Hypothèse de Densité',
    'td1.viz.sub_int.density_desc': 'Pour un hyperplan, ne pas être fermé signifie être "troué" partout. Son adhérence est alors obligée d\'être l\'espace complet.',
    'td1.viz.sub_int.vector_x': 'Vecteur x quelconque',

    'td1.viz.path.title': 'L\'Arc Continu sur un Espace Discret',
    'td1.viz.path.subtitle': 'Visualisez pourquoi une application continue vers {0, 1} est forcément constante.',
    'td1.viz.path.initial': 'Point Initial x',
    'td1.viz.path.final': 'Point Final y',
    'td1.viz.path.discrete_space': 'Espace Discret',
    'td1.viz.path.part_a': 'Partie A',
    'td1.viz.path.jump_impossible': 'Saut Impossible',
    'td1.viz.path.arc_title': 'Le Chemin Continu',
    'td1.viz.path.arc_desc': 'L\'arc γ est une ligne ininterrompue. Son image par f doit aussi être une ligne ininterrompue.',
    'td1.viz.path.bridge_title': 'L\'Espace sans "Pont"',
    'td1.viz.path.bridge_desc': 'Pour passer de 0 à 1, f devrait "sauter" ou passer par des valeurs intermédiaires. L\'espace discret n\'a pas de pont : le point reste bloqué.',

    'td1.viz.gln.title': 'La Barrière du Déterminant Nul',
    'td1.viz.gln.subtitle': 'Visualisez l\'impossibilité de passer de det > 0 à det < 0 dans GL_n.',
    'td1.viz.gln.mat_a': 'Matrice A (det > 0)',
    'td1.viz.gln.mat_b': 'Matrice B (det < 0)',
    'td1.viz.gln.forbidden': 'det = 0',
    'td1.viz.gln.tvi_title': 'Le TVI en Action',
    'td1.viz.gln.tvi_desc': 'Puisque le déterminant est continu, pour passer d\'une matrice de déterminant positif à une matrice de déterminant négatif, il faut obligatoirement passer par une matrice de déterminant nul.',
    'td1.viz.gln.fracture_title': 'La Fracture de GLn',
    'td1.viz.gln.fracture_desc': 'Or, les matrices de déterminant nul ne sont pas dans GL_n. L\'espace est donc "coupé en deux" par le vide : il ne peut pas être connexe par arcs.',
    'td1.viz.gln.mat_label': 'Matrice',

    'td1.ex3.q3a_title': '3.a Inégalité sur d(u_n, u_{n+p})',
    'td1.ex3.q3b_title': '3.b Suite de Cauchy',
  }
};

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
};
